name: "FoD IaC Scan"
description: "Runs a Fortify on Demand Scan of for Infrastrucure as Code files"
inputs:
  working_directory:
    required: false
    description: "Relative directory (from root of repository) from where to run commands"
    default: "."
  fod_url:
    required: false
    description: "FoD API URI"
    default: "https://ams.fortify.com"
  fod_api_url:
    required: false
    description: "FoD API URI"
    default: "https://api.ams.fortify.com"
  fod_client_id:
    required: true
    description: "FoD API Client Id"
  fod_client_secret:
    required: true
    description: "FoD API Client Secret"
  fod_app_name:
    required: true
    description: "FoD Application Name"
  fod_release_name:
    required: true
    description: "FoD Release Name"
  fod_parent_release_name:
    required: false
    description: "FoD Parent Release Name"
    default: "main"
outputs:
  fod_scan_id:
    description: "FoD Scan Id"
    value: ${{ steps.fod-sast-scan.outputs.fod_scan_id }}
runs:
  using: "composite"
  steps:
    # Java is required to run the various Fortify utilities.
    # Setup JDK 11 on host
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1.2.0
      with:
        export-path: true
        fcli: latest
        sc-client: latest
        fod-uploader: skip
        vuln-exporter: skip # assume it is run via source code scan
        bugtracker-utility: skip
    # Login to Fortify on Demand fcli session
    - name: Login fcli
      working-directory: ${{ env.BASE_DIR }}
      shell: bash
      run: |
        scancentral --version
        fcli --version
        fcli fod session login --url $FOD_API_URI --client-id $FOD_CLIENT_ID --client-secret $FOD_CLIENT_SECRET --session github-actions
      env:
        FOD_API_URI: ${{ inputs.fod_api_url }}
        FOD_CLIENT_ID: ${{ inputs.fod_client_id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod_client_secret }}
    # Create a new Fortify on Demand release for GitHub branch
    - name: Create FoD release
      id: create-release
      working-directory: ${{ env.BASE_DIR }}
      shell: bash
      run: |
        fcli fod release list --app "$FOD_APP_NAME" --session github-actions
        echo fcli fod release create "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --description "Created automatically from GitHub" --copy-from "${FOD_APP_NAME}:${FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session github-actions
        RELID=$(fcli fod release create "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --description "Created automatically from GitHub" --copy-from "${FOD_APP_NAME}:${FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session github-actions)
        echo "::debug::Created/Using fod_release_id=${RELID}"
        echo "release_id=${RELID}" >> $GITHUB_OUTPUT
      env:
        FOD_APP_NAME: ${{ inputs.fod_app_name }}
        FOD_RELEASE_NAME: ${{ inputs.fod_release_name }}
        FOD_PARENT_RELEASE_NAME: ${{ inputs.fod_parent_release_name }}
    # Zip up IaC files rather than use "scancentral package" command
    - name: Package IaC files
      uses: vimtor/action-zip@v1.1
      with:
        files: Dockerfile fortifydemoapp.bicep fortifydemoapp.parameters.json ./github
        dest: package.zip
    # Uncomment for debugging package contents    
    #- name: 'Upload Artifact'
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: "package"
    #    path: package.zip
    # Start Fortify on Demand SAST scan and wait until results complete.
      uses: actions/upload-artifact@v4
      with:
        name: "package"
        path: package.zip
    # Start Fortify on Demand SAST scan and wait until results complete.
    - name: Perform FoD SAST scan
      id: fod-sast-scan
      working-directory: ${{ env.BASE_DIR }}
      shell: bash
      run: |
        fcli fod sast-scan start --release "${FOD_RELEASE_NAME}" --notes "${FOD_SCAN_NOTES}" -f $PACKAGE_FILE --store curScan --session github-actions
        sleep 10
        echo "fod_scan_id=$(fcli util var get ::curScan::)" >> $GITHUB_OUTPUT
        fcli fod sast-scan wait-for ::curScan:: --session github-actions
      env:
        PACKAGE_FILE: "package.zip"
        FOD_RELEASE_NAME: ${{ format('{0}:{1}', inputs.fod_app_name, inputs.fod_release_name) }}
        FOD_SCAN_NOTES: "Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    # Logout/Close Fortify on Demand fcli session
    - name: Logout fcli
      shell: bash
      run: |
        fcli fod session logout --session github-actions
